-- Datenbanken Praktikum WS 2019/2020
-- Musterlösung - Create Table-Statements
-- Schritt 1) Erzeugung der Datenbank: db2 "create database funder"
-- Schritt 2) Verbindung zur Datenbank herstellen: db2 "connect to funder"
-- Schritt 3) Importierung der Beispieldaten: db2 -vtf create_tables.sql
 -- CLOB (1M)
 
 	
DROP TABLE users;
DROP TABLE accounts;	
DROP TABLE categorie;	
DROP TABLE project;	
DROP TABLE comments;	
DROP TABLE donate;	
DROP TABLE annotate;

CREATE TABLE users (
	id BIGSERIAL,
  	email VARCHAR(50) NOT NULL UNIQUE,
	username VARCHAR(50) NOT NULL UNIQUE,
  	surname VARCHAR(50) NOT NULL,
	firstname VARCHAR(50) NOT NULL,
	pssword VARCHAR(512) NOT NULL,
  	description VARCHAR(255),
	image bytea,
	createddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY (id)
);

CREATE TABLE fileimages (
	id bigint NOT NULL,
	image bytea,
  	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE
	
);

CREATE TABLE accounts (
  	owner bigint NOT NULL,
  	credit DECIMAL(10,2) NOT NULL,
 	secretnumber VARCHAR(10) NOT NULL,
  	PRIMARY KEY (owner),
  	FOREIGN KEY (owner) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE categories (
  	id serial,
  	name VARCHAR(50) NOT NULL,
  	icon bytea,
  	PRIMARY KEY (id)
);

CREATE TABLE project (
  	identifier SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  	title VARCHAR(50) NOT NULL,
  	description TEXT,
  	status VARCHAR(6) NOT NULL CHECK (status IN ('active', 'closed')) DEFAULT 'active',
  	fundinglimit DECIMAL(10,2) NOT NULL,
  	creatorid bigint NOT NULL,
  	predecessor SMALLINT,
  	categorieid SMALLINT NOT NULL,
	createddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY (identifier),
  	FOREIGN KEY (creatorId) REFERENCES users(id),
  	FOREIGN KEY (categorieid) REFERENCES categories(id),
  	FOREIGN KEY (predecessor) REFERENCES project(identifier)
);

CREATE TABLE comments (
  	id SMALLINT NOT NULL ,
  	text TEXT NOT NULL,
  	createddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  	visibility VARCHAR(6) NOT NULL CHECK (visibility IN ('public', 'privat')),
  	PRIMARY KEY (id)
);

CREATE TABLE donate (
	id BIGSERIAL,
  	donatorId bigint NOT NULL,
  	project SMALLINT NOT NULL,
  	donationamount DECIMAL(10,2) NOT NULL,
  	visibility VARCHAR(11) NOT NULL CHECK (visibility IN ('public', 'privat')),
	createddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY (id),
  	FOREIGN KEY (donatorId) REFERENCES users(id),
  	FOREIGN KEY (project) REFERENCES project(identifier)
);

CREATE TABLE annotate (
  	userId bigint NOT NULL,
  	project SMALLINT NOT NULL,
  	comments SMALLINT NOT NULL,
  	PRIMARY KEY (userId, project, comments),
  	FOREIGN KEY (userId) REFERENCES users(id),
  	FOREIGN KEY (project) REFERENCES project(identifier),
  	FOREIGN KEY (comments) REFERENCES comments(id)
);

